using System;
using System.Collections.Generic;
using System.Linq;

namespace PopulationGenerator
{
	public enum PersonNameOrigin
	{
		Common, // English?
		African,
		Chinese,
		French,
		Greek,
		Irish,
		Italian,
		Japanese,
		Latino,
		Middle_Eastern,
		Russian,
		Scandinavian,
		Slavic,
		South_Asian
	}

	public sealed class PersonName
	{
		public static readonly Tuple<string, PersonNameOrigin>[] LastNames = new Tuple<string, PersonNameOrigin>[] {
			Tuple.Create("Adams", PersonNameOrigin.Common),
			Tuple.Create("Albarn", PersonNameOrigin.Common),
			Tuple.Create("Aldrin", PersonNameOrigin.Common),
			Tuple.Create("Anderson", PersonNameOrigin.Common),
			Tuple.Create("Armstrong", PersonNameOrigin.Common),
			Tuple.Create("Bailey", PersonNameOrigin.Common),
			Tuple.Create("Baker", PersonNameOrigin.Common),
			Tuple.Create("Banks", PersonNameOrigin.Common),
			Tuple.Create("Barnes", PersonNameOrigin.Common),
			Tuple.Create("Bates", PersonNameOrigin.Common),
			Tuple.Create("Bell", PersonNameOrigin.Common),
			Tuple.Create("Bennett", PersonNameOrigin.Common),
			Tuple.Create("Black", PersonNameOrigin.Common),
			Tuple.Create("Bond", PersonNameOrigin.Common),
			Tuple.Create("Boulton", PersonNameOrigin.Common),
			Tuple.Create("Brennan", PersonNameOrigin.Common),
			Tuple.Create("Brooks", PersonNameOrigin.Common),
			Tuple.Create("Brown", PersonNameOrigin.Common),
			Tuple.Create("Bryant", PersonNameOrigin.Common),
			Tuple.Create("Butler", PersonNameOrigin.Common),
			Tuple.Create("Byrd", PersonNameOrigin.Common),
			Tuple.Create("Callaghan", PersonNameOrigin.Common),
			Tuple.Create("Campbell", PersonNameOrigin.Common),
			Tuple.Create("Carter", PersonNameOrigin.Common),
			Tuple.Create("Cash", PersonNameOrigin.Common),
			Tuple.Create("Church", PersonNameOrigin.Common),
			Tuple.Create("Clark", PersonNameOrigin.Common),
			Tuple.Create("Coleman", PersonNameOrigin.Common),
			Tuple.Create("Collins", PersonNameOrigin.Common),
			Tuple.Create("Cook", PersonNameOrigin.Common),
			Tuple.Create("Cooper", PersonNameOrigin.Common),
			Tuple.Create("Cox", PersonNameOrigin.Common),
			Tuple.Create("Cruz", PersonNameOrigin.Common),
			Tuple.Create("Cunningham", PersonNameOrigin.Common),
			Tuple.Create("Davis", PersonNameOrigin.Common),
			Tuple.Create("Diaz", PersonNameOrigin.Common),
			Tuple.Create("Duffus", PersonNameOrigin.Common),
			Tuple.Create("Dunn", PersonNameOrigin.Common),
			Tuple.Create("Edison", PersonNameOrigin.Common),
			Tuple.Create("Evans", PersonNameOrigin.Common),
			Tuple.Create("Fisher", PersonNameOrigin.Common),
			Tuple.Create("Fitzgerald", PersonNameOrigin.Common),
			Tuple.Create("Fitzpatrick", PersonNameOrigin.Common),
			Tuple.Create("Fleming", PersonNameOrigin.Common),
			Tuple.Create("Flores", PersonNameOrigin.Common),
			Tuple.Create("Ford", PersonNameOrigin.Common),
			Tuple.Create("Foster", PersonNameOrigin.Common),
			Tuple.Create("Fox", PersonNameOrigin.Common),
			Tuple.Create("Freeman", PersonNameOrigin.Common),
			Tuple.Create("Gallagher", PersonNameOrigin.Common),
			Tuple.Create("Garcia", PersonNameOrigin.Common),
			Tuple.Create("Gardner", PersonNameOrigin.Common),
			Tuple.Create("Gibson", PersonNameOrigin.Common),
			Tuple.Create("Goldberg", PersonNameOrigin.Common),
			Tuple.Create("Gomez", PersonNameOrigin.Common),
			Tuple.Create("Gonzales", PersonNameOrigin.Common),
			Tuple.Create("Gray", PersonNameOrigin.Common),
			Tuple.Create("Green", PersonNameOrigin.Common),
			Tuple.Create("Griffin", PersonNameOrigin.Common),
			Tuple.Create("Hall", PersonNameOrigin.Common),
			Tuple.Create("Hamilton", PersonNameOrigin.Common),
			Tuple.Create("Hanson", PersonNameOrigin.Common),
			Tuple.Create("Harris", PersonNameOrigin.Common),
			Tuple.Create("Hayes", PersonNameOrigin.Common),
			Tuple.Create("Henderson", PersonNameOrigin.Common),
			Tuple.Create("Hernandez", PersonNameOrigin.Common),
			Tuple.Create("Hicks", PersonNameOrigin.Common),
			Tuple.Create("Hill", PersonNameOrigin.Common),
			Tuple.Create("Holden", PersonNameOrigin.Common),
			Tuple.Create("Holland", PersonNameOrigin.Common),
			Tuple.Create("Howard", PersonNameOrigin.Common),
			Tuple.Create("Hughes", PersonNameOrigin.Common),
			Tuple.Create("Hunt", PersonNameOrigin.Common),
			Tuple.Create("Innes", PersonNameOrigin.Common),
			Tuple.Create("Irving", PersonNameOrigin.Common),
			Tuple.Create("Irwin", PersonNameOrigin.Common),
			Tuple.Create("Jackson", PersonNameOrigin.Common),
			Tuple.Create("Jamieson", PersonNameOrigin.Common),
			Tuple.Create("Jenkins", PersonNameOrigin.Common),
			Tuple.Create("Jewell", PersonNameOrigin.Common),
			Tuple.Create("Johnson", PersonNameOrigin.Common),
			Tuple.Create("Jones", PersonNameOrigin.Common),
			Tuple.Create("Keane", PersonNameOrigin.Common),
			Tuple.Create("King", PersonNameOrigin.Common),
			Tuple.Create("Klein", PersonNameOrigin.Common),
			Tuple.Create("Lane", PersonNameOrigin.Common),
			Tuple.Create("Lawson", PersonNameOrigin.Common),
			Tuple.Create("Lee", PersonNameOrigin.Common),
			Tuple.Create("Long", PersonNameOrigin.Common),
			Tuple.Create("Lynch", PersonNameOrigin.Common),
			Tuple.Create("Macpherson", PersonNameOrigin.Common),
			Tuple.Create("Mars", PersonNameOrigin.Common),
			Tuple.Create("Mason", PersonNameOrigin.Common),
			Tuple.Create("Maynard", PersonNameOrigin.Common),
			Tuple.Create("McDonald", PersonNameOrigin.Common),
			Tuple.Create("McGregor", PersonNameOrigin.Common),
			Tuple.Create("Miller", PersonNameOrigin.Common),
			Tuple.Create("Mitcheson", PersonNameOrigin.Common),
			Tuple.Create("Moore", PersonNameOrigin.Common),
			Tuple.Create("Morales", PersonNameOrigin.Common),
			Tuple.Create("Morgan", PersonNameOrigin.Common),
			Tuple.Create("Morris", PersonNameOrigin.Common),
			Tuple.Create("Murphy", PersonNameOrigin.Common),
			Tuple.Create("Myers", PersonNameOrigin.Common),
			Tuple.Create("Nelson", PersonNameOrigin.Common),
			Tuple.Create("Newman", PersonNameOrigin.Common),
			Tuple.Create("Nguyen", PersonNameOrigin.Common),
			Tuple.Create("Noone", PersonNameOrigin.Common),
			Tuple.Create("O'Brien", PersonNameOrigin.Common),
			Tuple.Create("O'Toole", PersonNameOrigin.Common),
			Tuple.Create("Olson", PersonNameOrigin.Common),
			Tuple.Create("Ortega", PersonNameOrigin.Common),
			Tuple.Create("Ortiz", PersonNameOrigin.Common),
			Tuple.Create("Parker", PersonNameOrigin.Common),
			Tuple.Create("Patterson", PersonNameOrigin.Common),
			Tuple.Create("Payne", PersonNameOrigin.Common),
			Tuple.Create("Peacock", PersonNameOrigin.Common),
			Tuple.Create("Perez", PersonNameOrigin.Common),
			Tuple.Create("Peterson", PersonNameOrigin.Common),
			Tuple.Create("Phillips", PersonNameOrigin.Common),
			Tuple.Create("Poole", PersonNameOrigin.Common),
			Tuple.Create("Powell", PersonNameOrigin.Common),
			Tuple.Create("Price", PersonNameOrigin.Common),
			Tuple.Create("Prince", PersonNameOrigin.Common),
			Tuple.Create("Pritchard", PersonNameOrigin.Common),
			Tuple.Create("Ramirez", PersonNameOrigin.Common),
			Tuple.Create("Ramos", PersonNameOrigin.Common),
			Tuple.Create("Reed", PersonNameOrigin.Common),
			Tuple.Create("Reyes", PersonNameOrigin.Common),
			Tuple.Create("Reynolds", PersonNameOrigin.Common),
			Tuple.Create("Richardson", PersonNameOrigin.Common),
			Tuple.Create("Rivera", PersonNameOrigin.Common),
			Tuple.Create("Robertson", PersonNameOrigin.Common),
			Tuple.Create("Robinson", PersonNameOrigin.Common),
			Tuple.Create("Rodgers", PersonNameOrigin.Common),
			Tuple.Create("Rodriguez", PersonNameOrigin.Common),
			Tuple.Create("Rollins", PersonNameOrigin.Common),
			Tuple.Create("Rush", PersonNameOrigin.Common),
			Tuple.Create("Sanchez", PersonNameOrigin.Common),
			Tuple.Create("Sanders", PersonNameOrigin.Common),
			Tuple.Create("Schaefer", PersonNameOrigin.Common),
			Tuple.Create("Schmidt", PersonNameOrigin.Common),
			Tuple.Create("Schultz", PersonNameOrigin.Common),
			Tuple.Create("Simmons", PersonNameOrigin.Common),
			Tuple.Create("Simpson", PersonNameOrigin.Common),
			Tuple.Create("Smith", PersonNameOrigin.Common),
			Tuple.Create("Snyder", PersonNameOrigin.Common),
			Tuple.Create("Spencer", PersonNameOrigin.Common),
			Tuple.Create("Sterling", PersonNameOrigin.Common),
			Tuple.Create("Stewart", PersonNameOrigin.Common),
			Tuple.Create("Stone", PersonNameOrigin.Common),
			Tuple.Create("Sullivan", PersonNameOrigin.Common),
			Tuple.Create("Taylor", PersonNameOrigin.Common),
			Tuple.Create("Temple", PersonNameOrigin.Common),
			Tuple.Create("Thompson", PersonNameOrigin.Common),
			Tuple.Create("Thurston", PersonNameOrigin.Common),
			Tuple.Create("Torres", PersonNameOrigin.Common),
			Tuple.Create("Tucker", PersonNameOrigin.Common),
			Tuple.Create("Turner", PersonNameOrigin.Common),
			Tuple.Create("Walker", PersonNameOrigin.Common),
			Tuple.Create("Ward", PersonNameOrigin.Common),
			Tuple.Create("Washington", PersonNameOrigin.Common),
			Tuple.Create("Watson", PersonNameOrigin.Common),
			Tuple.Create("Wayne", PersonNameOrigin.Common),
			Tuple.Create("West", PersonNameOrigin.Common),
			Tuple.Create("White", PersonNameOrigin.Common),
			Tuple.Create("Wilson", PersonNameOrigin.Common),
			Tuple.Create("Wood", PersonNameOrigin.Common),
			Tuple.Create("Wright", PersonNameOrigin.Common),
			Tuple.Create("Young", PersonNameOrigin.Common),
			Tuple.Create("Azikiwe", PersonNameOrigin.African),
			Tuple.Create("Balewa", PersonNameOrigin.African),
			Tuple.Create("Dimka", PersonNameOrigin.African),
			Tuple.Create("Igwe", PersonNameOrigin.African),
			Tuple.Create("Jang", PersonNameOrigin.African),
			Tuple.Create("Magoro", PersonNameOrigin.African),
			Tuple.Create("Nzeogwu", PersonNameOrigin.African),
			Tuple.Create("Obasanjo", PersonNameOrigin.African),
			Tuple.Create("Okeke", PersonNameOrigin.African),
			Tuple.Create("Sekibo", PersonNameOrigin.African),
			Tuple.Create("Chén", PersonNameOrigin.Chinese),
			Tuple.Create("Guō", PersonNameOrigin.Chinese),
			Tuple.Create("Huáng", PersonNameOrigin.Chinese),
			Tuple.Create("Liáng", PersonNameOrigin.Chinese),
			Tuple.Create("Sūn", PersonNameOrigin.Chinese),
			Tuple.Create("Wáng", PersonNameOrigin.Chinese),
			Tuple.Create("Xú", PersonNameOrigin.Chinese),
			Tuple.Create("Yáng", PersonNameOrigin.Chinese),
			Tuple.Create("Zhāng", PersonNameOrigin.Chinese),
			Tuple.Create("Zhào", PersonNameOrigin.Chinese),
			Tuple.Create("Chevalier", PersonNameOrigin.French),
			Tuple.Create("De Sauveterre", PersonNameOrigin.French),
			Tuple.Create("Guillaume", PersonNameOrigin.French),
			Tuple.Create("Lacroix", PersonNameOrigin.French),
			Tuple.Create("Le Roux", PersonNameOrigin.French),
			Tuple.Create("Lefebvre", PersonNameOrigin.French),
			Tuple.Create("Mathieu", PersonNameOrigin.French),
			Tuple.Create("Moreau", PersonNameOrigin.French),
			Tuple.Create("Renaud", PersonNameOrigin.French),
			Tuple.Create("Rousseau", PersonNameOrigin.French),
			Tuple.Create("Antoniou", PersonNameOrigin.Greek),
			Tuple.Create("Dimitriou", PersonNameOrigin.Greek),
			Tuple.Create("Korba", PersonNameOrigin.Greek),
			Tuple.Create("Leva", PersonNameOrigin.Greek),
			Tuple.Create("Moros", PersonNameOrigin.Greek),
			Tuple.Create("Papadopoulos", PersonNameOrigin.Greek),
			Tuple.Create("Poulos", PersonNameOrigin.Greek),
			Tuple.Create("Sarantos", PersonNameOrigin.Greek),
			Tuple.Create("Vassos", PersonNameOrigin.Greek),
			Tuple.Create("Zervos", PersonNameOrigin.Greek),
			Tuple.Create("Boyle", PersonNameOrigin.Irish),
			Tuple.Create("Daly", PersonNameOrigin.Irish),
			Tuple.Create("Dunne", PersonNameOrigin.Irish),
			Tuple.Create("Flanagan", PersonNameOrigin.Irish),
			Tuple.Create("MacDermott", PersonNameOrigin.Irish),
			Tuple.Create("Maher", PersonNameOrigin.Irish),
			Tuple.Create("McCarthy", PersonNameOrigin.Irish),
			Tuple.Create("O'Callaghan", PersonNameOrigin.Irish),
			Tuple.Create("O'Shea", PersonNameOrigin.Irish),
			Tuple.Create("Sheehan", PersonNameOrigin.Irish),
			Tuple.Create("Addario", PersonNameOrigin.Italian),
			Tuple.Create("Bianchi", PersonNameOrigin.Italian),
			Tuple.Create("Crosato", PersonNameOrigin.Italian),
			Tuple.Create("Giordano", PersonNameOrigin.Italian),
			Tuple.Create("Lombardi", PersonNameOrigin.Italian),
			Tuple.Create("Mancino", PersonNameOrigin.Italian),
			Tuple.Create("Rognoni", PersonNameOrigin.Italian),
			Tuple.Create("Romani", PersonNameOrigin.Italian),
			Tuple.Create("Verde", PersonNameOrigin.Italian),
			Tuple.Create("Zanetti", PersonNameOrigin.Italian),
			Tuple.Create("Fujita", PersonNameOrigin.Japanese),
			Tuple.Create("Hayashi", PersonNameOrigin.Japanese),
			Tuple.Create("Inoue", PersonNameOrigin.Japanese),
			Tuple.Create("Ito", PersonNameOrigin.Japanese),
			Tuple.Create("Okada", PersonNameOrigin.Japanese),
			Tuple.Create("Saito", PersonNameOrigin.Japanese),
			Tuple.Create("Suzuki", PersonNameOrigin.Japanese),
			Tuple.Create("Takahashi", PersonNameOrigin.Japanese),
			Tuple.Create("Watanabe", PersonNameOrigin.Japanese),
			Tuple.Create("Yamada", PersonNameOrigin.Japanese),
			Tuple.Create("Alvarado", PersonNameOrigin.Latino),
			Tuple.Create("Cardenas", PersonNameOrigin.Latino),
			Tuple.Create("Granados", PersonNameOrigin.Latino),
			Tuple.Create("Guzman", PersonNameOrigin.Latino),
			Tuple.Create("Hererra", PersonNameOrigin.Latino),
			Tuple.Create("Montoya", PersonNameOrigin.Latino),
			Tuple.Create("Rios", PersonNameOrigin.Latino),
			Tuple.Create("Segura", PersonNameOrigin.Latino),
			Tuple.Create("Trujillo", PersonNameOrigin.Latino),
			Tuple.Create("Vazquez", PersonNameOrigin.Latino),
			Tuple.Create("Abdel", PersonNameOrigin.Middle_Eastern),
			Tuple.Create("Armanjani", PersonNameOrigin.Middle_Eastern),
			Tuple.Create("Hassan", PersonNameOrigin.Middle_Eastern),
			Tuple.Create("Jabir", PersonNameOrigin.Middle_Eastern),
			Tuple.Create("Khatib", PersonNameOrigin.Middle_Eastern),
			Tuple.Create("Khoury", PersonNameOrigin.Middle_Eastern),
			Tuple.Create("Murat", PersonNameOrigin.Middle_Eastern),
			Tuple.Create("Qasim", PersonNameOrigin.Middle_Eastern),
			Tuple.Create("Salah", PersonNameOrigin.Middle_Eastern),
			Tuple.Create("Shaheen", PersonNameOrigin.Middle_Eastern),
			Tuple.Create("Egorov", PersonNameOrigin.Russian),
			Tuple.Create("Ivanov", PersonNameOrigin.Russian),
			Tuple.Create("Kozlov", PersonNameOrigin.Russian),
			Tuple.Create("Lebedev", PersonNameOrigin.Russian),
			Tuple.Create("Mikhailov", PersonNameOrigin.Russian),
			Tuple.Create("Pavlov", PersonNameOrigin.Russian),
			Tuple.Create("Petrov", PersonNameOrigin.Russian),
			Tuple.Create("Popov", PersonNameOrigin.Russian),
			Tuple.Create("Sokolov", PersonNameOrigin.Russian),
			Tuple.Create("Vasiliev", PersonNameOrigin.Russian),
			Tuple.Create("Andreassen", PersonNameOrigin.Scandinavian),
			Tuple.Create("Berg", PersonNameOrigin.Scandinavian),
			Tuple.Create("Hagen", PersonNameOrigin.Scandinavian),
			Tuple.Create("Halvorsen", PersonNameOrigin.Scandinavian),
			Tuple.Create("Jørgensen", PersonNameOrigin.Scandinavian),
			Tuple.Create("Karlsen", PersonNameOrigin.Scandinavian),
			Tuple.Create("Magnusson", PersonNameOrigin.Scandinavian),
			Tuple.Create("Olofsson", PersonNameOrigin.Scandinavian),
			Tuple.Create("Rasmussen", PersonNameOrigin.Scandinavian),
			Tuple.Create("Sørensen", PersonNameOrigin.Scandinavian),
			Tuple.Create("Balog", PersonNameOrigin.Slavic),
			Tuple.Create("Beridze", PersonNameOrigin.Slavic),
			Tuple.Create("Damcevski", PersonNameOrigin.Slavic),
			Tuple.Create("Demirović", PersonNameOrigin.Slavic),
			Tuple.Create("Horvat", PersonNameOrigin.Slavic),
			Tuple.Create("Jovanović", PersonNameOrigin.Slavic),
			Tuple.Create("Kranjcic", PersonNameOrigin.Slavic),
			Tuple.Create("Novák", PersonNameOrigin.Slavic),
			Tuple.Create("Rozman", PersonNameOrigin.Slavic),
			Tuple.Create("Wójcik", PersonNameOrigin.Slavic),
			Tuple.Create("Choudhary", PersonNameOrigin.South_Asian),
			Tuple.Create("Devi", PersonNameOrigin.South_Asian),
			Tuple.Create("Gupta", PersonNameOrigin.South_Asian),
			Tuple.Create("Kumar", PersonNameOrigin.South_Asian),
			Tuple.Create("Nibhanupudi", PersonNameOrigin.South_Asian),
			Tuple.Create("Patel", PersonNameOrigin.South_Asian),
			Tuple.Create("Rahman", PersonNameOrigin.South_Asian),
			Tuple.Create("Singh", PersonNameOrigin.South_Asian),
			Tuple.Create("Srinivasan", PersonNameOrigin.South_Asian),
			Tuple.Create("Wazed", PersonNameOrigin.South_Asian)
		};
		public static readonly Tuple<string, PersonNameOrigin>[] MaleNames = new Tuple<string, PersonNameOrigin>[] {
			Tuple.Create("Aaron", PersonNameOrigin.Common),
			Tuple.Create("Adam", PersonNameOrigin.Common),
			Tuple.Create("Aiden", PersonNameOrigin.Common),
			Tuple.Create("Andrew", PersonNameOrigin.Common),
			Tuple.Create("Anthony", PersonNameOrigin.Common),
			Tuple.Create("Arnold", PersonNameOrigin.Common),
			Tuple.Create("Barry", PersonNameOrigin.Common),
			Tuple.Create("Benjamin", PersonNameOrigin.Common),
			Tuple.Create("Bernard", PersonNameOrigin.Common),
			Tuple.Create("Blake", PersonNameOrigin.Common),
			Tuple.Create("Bradley", PersonNameOrigin.Common),
			Tuple.Create("Brandon", PersonNameOrigin.Common),
			Tuple.Create("Brett", PersonNameOrigin.Common),
			Tuple.Create("Brian", PersonNameOrigin.Common),
			Tuple.Create("Bruce", PersonNameOrigin.Common),
			Tuple.Create("Byron", PersonNameOrigin.Common),
			Tuple.Create("Caleb", PersonNameOrigin.Common),
			Tuple.Create("Calvin", PersonNameOrigin.Common),
			Tuple.Create("Cameron", PersonNameOrigin.Common),
			Tuple.Create("Carl", PersonNameOrigin.Common),
			Tuple.Create("Chad", PersonNameOrigin.Common),
			Tuple.Create("Christian", PersonNameOrigin.Common),
			Tuple.Create("Christopher", PersonNameOrigin.Common),
			Tuple.Create("Clint", PersonNameOrigin.Common),
			Tuple.Create("Cody", PersonNameOrigin.Common),
			Tuple.Create("Colin", PersonNameOrigin.Common),
			Tuple.Create("Cooper", PersonNameOrigin.Common),
			Tuple.Create("Corey", PersonNameOrigin.Common),
			Tuple.Create("Craig", PersonNameOrigin.Common),
			Tuple.Create("Curtis", PersonNameOrigin.Common),
			Tuple.Create("Dale", PersonNameOrigin.Common),
			Tuple.Create("Damien", PersonNameOrigin.Common),
			Tuple.Create("Daniel", PersonNameOrigin.Common),
			Tuple.Create("Darren", PersonNameOrigin.Common),
			Tuple.Create("David", PersonNameOrigin.Common),
			Tuple.Create("Dawson", PersonNameOrigin.Common),
			Tuple.Create("Dean", PersonNameOrigin.Common),
			Tuple.Create("Dennis", PersonNameOrigin.Common),
			Tuple.Create("Derek", PersonNameOrigin.Common),
			Tuple.Create("Dexter", PersonNameOrigin.Common),
			Tuple.Create("Dominic", PersonNameOrigin.Common),
			Tuple.Create("Donald", PersonNameOrigin.Common),
			Tuple.Create("Douglas", PersonNameOrigin.Common),
			Tuple.Create("Drake", PersonNameOrigin.Common),
			Tuple.Create("Dustin", PersonNameOrigin.Common),
			Tuple.Create("Dwayne", PersonNameOrigin.Common),
			Tuple.Create("Dwight", PersonNameOrigin.Common),
			Tuple.Create("Dylan", PersonNameOrigin.Common),
			Tuple.Create("Edward", PersonNameOrigin.Common),
			Tuple.Create("Eli", PersonNameOrigin.Common),
			Tuple.Create("Ernie", PersonNameOrigin.Common),
			Tuple.Create("Ethan", PersonNameOrigin.Common),
			Tuple.Create("Eugene", PersonNameOrigin.Common),
			Tuple.Create("Evan", PersonNameOrigin.Common),
			Tuple.Create("Forrest", PersonNameOrigin.Common),
			Tuple.Create("Fred", PersonNameOrigin.Common),
			Tuple.Create("Gabriel", PersonNameOrigin.Common),
			Tuple.Create("Gary", PersonNameOrigin.Common),
			Tuple.Create("George", PersonNameOrigin.Common),
			Tuple.Create("Gerard", PersonNameOrigin.Common),
			Tuple.Create("Gilbert", PersonNameOrigin.Common),
			Tuple.Create("Glen", PersonNameOrigin.Common),
			Tuple.Create("Gordon", PersonNameOrigin.Common),
			Tuple.Create("Grant", PersonNameOrigin.Common),
			Tuple.Create("Greg", PersonNameOrigin.Common),
			Tuple.Create("Harry", PersonNameOrigin.Common),
			Tuple.Create("Hayden", PersonNameOrigin.Common),
			Tuple.Create("Hector", PersonNameOrigin.Common),
			Tuple.Create("Henry", PersonNameOrigin.Common),
			Tuple.Create("Hugh", PersonNameOrigin.Common),
			Tuple.Create("Hugo", PersonNameOrigin.Common),
			Tuple.Create("Hunter", PersonNameOrigin.Common),
			Tuple.Create("Ian", PersonNameOrigin.Common),
			Tuple.Create("Jack", PersonNameOrigin.Common),
			Tuple.Create("Jacob", PersonNameOrigin.Common),
			Tuple.Create("Jaden", PersonNameOrigin.Common),
			Tuple.Create("James", PersonNameOrigin.Common),
			Tuple.Create("Jarrod", PersonNameOrigin.Common),
			Tuple.Create("Jason", PersonNameOrigin.Common),
			Tuple.Create("Jeffery", PersonNameOrigin.Common),
			Tuple.Create("Jerry", PersonNameOrigin.Common),
			Tuple.Create("Joel", PersonNameOrigin.Common),
			Tuple.Create("John", PersonNameOrigin.Common),
			Tuple.Create("Jonah", PersonNameOrigin.Common),
			Tuple.Create("Joseph", PersonNameOrigin.Common),
			Tuple.Create("Joshua", PersonNameOrigin.Common),
			Tuple.Create("Julian", PersonNameOrigin.Common),
			Tuple.Create("Justin", PersonNameOrigin.Common),
			Tuple.Create("Keith", PersonNameOrigin.Common),
			Tuple.Create("Ken", PersonNameOrigin.Common),
			Tuple.Create("Kevin", PersonNameOrigin.Common),
			Tuple.Create("Kyle", PersonNameOrigin.Common),
			Tuple.Create("Lance", PersonNameOrigin.Common),
			Tuple.Create("Larry", PersonNameOrigin.Common),
			Tuple.Create("Lenny", PersonNameOrigin.Common),
			Tuple.Create("Liam", PersonNameOrigin.Common),
			Tuple.Create("Lionel", PersonNameOrigin.Common),
			Tuple.Create("Llewyn", PersonNameOrigin.Common),
			Tuple.Create("Lloyd", PersonNameOrigin.Common),
			Tuple.Create("Louis", PersonNameOrigin.Common),
			Tuple.Create("Lucas", PersonNameOrigin.Common),
			Tuple.Create("Mark", PersonNameOrigin.Common),
			Tuple.Create("Marshall", PersonNameOrigin.Common),
			Tuple.Create("Martin", PersonNameOrigin.Common),
			Tuple.Create("Marvin", PersonNameOrigin.Common),
			Tuple.Create("Matthew", PersonNameOrigin.Common),
			Tuple.Create("Max", PersonNameOrigin.Common),
			Tuple.Create("Michael", PersonNameOrigin.Common),
			Tuple.Create("Milton", PersonNameOrigin.Common),
			Tuple.Create("Mitchell", PersonNameOrigin.Common),
			Tuple.Create("Nathan", PersonNameOrigin.Common),
			Tuple.Create("Neil", PersonNameOrigin.Common),
			Tuple.Create("Nicholas", PersonNameOrigin.Common),
			Tuple.Create("Noah", PersonNameOrigin.Common),
			Tuple.Create("Noel", PersonNameOrigin.Common),
			Tuple.Create("Norman", PersonNameOrigin.Common),
			Tuple.Create("Oliver", PersonNameOrigin.Common),
			Tuple.Create("Oscar", PersonNameOrigin.Common),
			Tuple.Create("Owen", PersonNameOrigin.Common),
			Tuple.Create("Patrick", PersonNameOrigin.Common),
			Tuple.Create("Paul", PersonNameOrigin.Common),
			Tuple.Create("Percy", PersonNameOrigin.Common),
			Tuple.Create("Peter", PersonNameOrigin.Common),
			Tuple.Create("Phil", PersonNameOrigin.Common),
			Tuple.Create("Quentin", PersonNameOrigin.Common),
			Tuple.Create("Ralph", PersonNameOrigin.Common),
			Tuple.Create("Randy", PersonNameOrigin.Common),
			Tuple.Create("Raymond", PersonNameOrigin.Common),
			Tuple.Create("Rex", PersonNameOrigin.Common),
			Tuple.Create("Robert", PersonNameOrigin.Common),
			Tuple.Create("Rocky", PersonNameOrigin.Common),
			Tuple.Create("Roderick", PersonNameOrigin.Common),
			Tuple.Create("Roger", PersonNameOrigin.Common),
			Tuple.Create("Ron", PersonNameOrigin.Common),
			Tuple.Create("Ross", PersonNameOrigin.Common),
			Tuple.Create("Roy", PersonNameOrigin.Common),
			Tuple.Create("Ruben", PersonNameOrigin.Common),
			Tuple.Create("Rudy", PersonNameOrigin.Common),
			Tuple.Create("Rufus", PersonNameOrigin.Common),
			Tuple.Create("Russell", PersonNameOrigin.Common),
			Tuple.Create("Ryan", PersonNameOrigin.Common),
			Tuple.Create("Samuel", PersonNameOrigin.Common),
			Tuple.Create("Scott", PersonNameOrigin.Common),
			Tuple.Create("Sebastian", PersonNameOrigin.Common),
			Tuple.Create("Seth", PersonNameOrigin.Common),
			Tuple.Create("Shane", PersonNameOrigin.Common),
			Tuple.Create("Shaun", PersonNameOrigin.Common),
			Tuple.Create("Simon", PersonNameOrigin.Common),
			Tuple.Create("Stanley", PersonNameOrigin.Common),
			Tuple.Create("Steven", PersonNameOrigin.Common),
			Tuple.Create("Terry", PersonNameOrigin.Common),
			Tuple.Create("Thomas", PersonNameOrigin.Common),
			Tuple.Create("Tim", PersonNameOrigin.Common),
			Tuple.Create("Toby", PersonNameOrigin.Common),
			Tuple.Create("Todd", PersonNameOrigin.Common),
			Tuple.Create("Travis", PersonNameOrigin.Common),
			Tuple.Create("Trevor", PersonNameOrigin.Common),
			Tuple.Create("Tristan", PersonNameOrigin.Common),
			Tuple.Create("Troy", PersonNameOrigin.Common),
			Tuple.Create("Tyler", PersonNameOrigin.Common),
			Tuple.Create("Tyrone", PersonNameOrigin.Common),
			Tuple.Create("Tyson", PersonNameOrigin.Common),
			Tuple.Create("Vincent", PersonNameOrigin.Common),
			Tuple.Create("Wade", PersonNameOrigin.Common),
			Tuple.Create("Warren", PersonNameOrigin.Common),
			Tuple.Create("Wayne", PersonNameOrigin.Common),
			Tuple.Create("William", PersonNameOrigin.Common),
			Tuple.Create("Winston", PersonNameOrigin.Common),
			Tuple.Create("Xavier", PersonNameOrigin.Common),
			Tuple.Create("Zachary", PersonNameOrigin.Common),
			Tuple.Create("Adebayo", PersonNameOrigin.African),
			Tuple.Create("Dembe", PersonNameOrigin.African),
			Tuple.Create("Gowon", PersonNameOrigin.African),
			Tuple.Create("Idi", PersonNameOrigin.African),
			Tuple.Create("Jibade", PersonNameOrigin.African),
			Tuple.Create("Kobe", PersonNameOrigin.African),
			Tuple.Create("Nkrumah", PersonNameOrigin.African),
			Tuple.Create("Sabola", PersonNameOrigin.African),
			Tuple.Create("Teka", PersonNameOrigin.African),
			Tuple.Create("Zawadi", PersonNameOrigin.African),
			Tuple.Create("Cheng", PersonNameOrigin.Chinese),
			Tuple.Create("Feng", PersonNameOrigin.Chinese),
			Tuple.Create("Hong", PersonNameOrigin.Chinese),
			Tuple.Create("Jaw-Long", PersonNameOrigin.Chinese),
			Tuple.Create("Ming-húa", PersonNameOrigin.Chinese),
			Tuple.Create("Sueh-yén", PersonNameOrigin.Chinese),
			Tuple.Create("Tao", PersonNameOrigin.Chinese),
			Tuple.Create("Weiming", PersonNameOrigin.Chinese),
			Tuple.Create("Xiu", PersonNameOrigin.Chinese),
			Tuple.Create("Yang", PersonNameOrigin.Chinese),
			Tuple.Create("Beauregard", PersonNameOrigin.French),
			Tuple.Create("Cheyne", PersonNameOrigin.French),
			Tuple.Create("Florian", PersonNameOrigin.French),
			Tuple.Create("Gaston", PersonNameOrigin.French),
			Tuple.Create("Marcel", PersonNameOrigin.French),
			Tuple.Create("Norville", PersonNameOrigin.French),
			Tuple.Create("Pierpont", PersonNameOrigin.French),
			Tuple.Create("Pierre", PersonNameOrigin.French),
			Tuple.Create("Renard", PersonNameOrigin.French),
			Tuple.Create("Sinclair", PersonNameOrigin.French),
			Tuple.Create("Adonis", PersonNameOrigin.Greek),
			Tuple.Create("Vasilis", PersonNameOrigin.Greek),
			Tuple.Create("Spiros", PersonNameOrigin.Greek),
			Tuple.Create("Demetrius", PersonNameOrigin.Greek),
			Tuple.Create("Theodoros", PersonNameOrigin.Greek),
			Tuple.Create("Konstantinos", PersonNameOrigin.Greek),
			Tuple.Create("Lefteris", PersonNameOrigin.Greek),
			Tuple.Create("Manos", PersonNameOrigin.Greek),
			Tuple.Create("Yannis", PersonNameOrigin.Greek),
			Tuple.Create("Stavros", PersonNameOrigin.Greek),
			Tuple.Create("Ciaran", PersonNameOrigin.Irish),
			Tuple.Create("Cillian", PersonNameOrigin.Irish),
			Tuple.Create("Cormac", PersonNameOrigin.Irish),
			Tuple.Create("Darragh", PersonNameOrigin.Irish),
			Tuple.Create("Eoin", PersonNameOrigin.Irish),
			Tuple.Create("Finn", PersonNameOrigin.Irish),
			Tuple.Create("Lorcán", PersonNameOrigin.Irish),
			Tuple.Create("Niall", PersonNameOrigin.Irish),
			Tuple.Create("Oisin", PersonNameOrigin.Irish),
			Tuple.Create("Tighe", PersonNameOrigin.Irish),
			Tuple.Create("Alfredo", PersonNameOrigin.Italian),
			Tuple.Create("Franco", PersonNameOrigin.Italian),
			Tuple.Create("Giovanni", PersonNameOrigin.Italian),
			Tuple.Create("Giuseppe", PersonNameOrigin.Italian),
			Tuple.Create("Leonardo", PersonNameOrigin.Italian),
			Tuple.Create("Lorenzo", PersonNameOrigin.Italian),
			Tuple.Create("Luigi", PersonNameOrigin.Italian),
			Tuple.Create("Mario", PersonNameOrigin.Italian),
			Tuple.Create("Salvatore", PersonNameOrigin.Italian),
			Tuple.Create("Sergio", PersonNameOrigin.Italian),
			Tuple.Create("Asahi", PersonNameOrigin.Japanese),
			Tuple.Create("Haruto", PersonNameOrigin.Japanese),
			Tuple.Create("Itsuki", PersonNameOrigin.Japanese),
			Tuple.Create("Joji", PersonNameOrigin.Japanese),
			Tuple.Create("Kaito", PersonNameOrigin.Japanese),
			Tuple.Create("Manato", PersonNameOrigin.Japanese),
			Tuple.Create("Reo", PersonNameOrigin.Japanese),
			Tuple.Create("Riku", PersonNameOrigin.Japanese),
			Tuple.Create("Ryosei", PersonNameOrigin.Japanese),
			Tuple.Create("Yuuto", PersonNameOrigin.Japanese),
			Tuple.Create("Carlos", PersonNameOrigin.Latino),
			Tuple.Create("Diego", PersonNameOrigin.Latino),
			Tuple.Create("Eduardo", PersonNameOrigin.Latino),
			Tuple.Create("Enrique", PersonNameOrigin.Latino),
			Tuple.Create("Fernando", PersonNameOrigin.Latino),
			Tuple.Create("Jesus", PersonNameOrigin.Latino),
			Tuple.Create("José", PersonNameOrigin.Latino),
			Tuple.Create("Juan", PersonNameOrigin.Latino),
			Tuple.Create("Manuel", PersonNameOrigin.Latino),
			Tuple.Create("Ramon", PersonNameOrigin.Latino),
			Tuple.Create("Abdul", PersonNameOrigin.Middle_Eastern),
			Tuple.Create("Ahmed", PersonNameOrigin.Middle_Eastern),
			Tuple.Create("Isaiah", PersonNameOrigin.Middle_Eastern),
			Tuple.Create("Jamal", PersonNameOrigin.Middle_Eastern),
			Tuple.Create("Karim", PersonNameOrigin.Middle_Eastern),
			Tuple.Create("Malik", PersonNameOrigin.Middle_Eastern),
			Tuple.Create("Mohammed", PersonNameOrigin.Middle_Eastern),
			Tuple.Create("Nazeem", PersonNameOrigin.Middle_Eastern),
			Tuple.Create("Sharif", PersonNameOrigin.Middle_Eastern),
			Tuple.Create("Yousef", PersonNameOrigin.Middle_Eastern),
			Tuple.Create("Boris", PersonNameOrigin.Russian),
			Tuple.Create("Ivan", PersonNameOrigin.Russian),
			Tuple.Create("Leonid", PersonNameOrigin.Russian),
			Tuple.Create("Mikhail", PersonNameOrigin.Russian),
			Tuple.Create("Pavel", PersonNameOrigin.Russian),
			Tuple.Create("Rostislav", PersonNameOrigin.Russian),
			Tuple.Create("Sergei", PersonNameOrigin.Russian),
			Tuple.Create("Viktor", PersonNameOrigin.Russian),
			Tuple.Create("Vitaly", PersonNameOrigin.Russian),
			Tuple.Create("Vladimir", PersonNameOrigin.Russian),
			Tuple.Create("Anders", PersonNameOrigin.Scandinavian),
			Tuple.Create("Emil", PersonNameOrigin.Scandinavian),
			Tuple.Create("Erik", PersonNameOrigin.Scandinavian),
			Tuple.Create("Felix", PersonNameOrigin.Scandinavian),
			Tuple.Create("Lalli", PersonNameOrigin.Scandinavian),
			Tuple.Create("Mikkel", PersonNameOrigin.Scandinavian),
			Tuple.Create("Reynir", PersonNameOrigin.Scandinavian),
			Tuple.Create("Rolf", PersonNameOrigin.Scandinavian),
			Tuple.Create("Torbjörn", PersonNameOrigin.Scandinavian),
			Tuple.Create("Tord", PersonNameOrigin.Scandinavian),
			Tuple.Create("Andrej", PersonNameOrigin.Slavic),
			Tuple.Create("Danek", PersonNameOrigin.Slavic),
			Tuple.Create("Jaromir", PersonNameOrigin.Slavic),
			Tuple.Create("Laszlo", PersonNameOrigin.Slavic),
			Tuple.Create("Miko", PersonNameOrigin.Slavic),
			Tuple.Create("Oriel", PersonNameOrigin.Slavic),
			Tuple.Create("Rorric", PersonNameOrigin.Slavic),
			Tuple.Create("Slavik", PersonNameOrigin.Slavic),
			Tuple.Create("Stanislaus", PersonNameOrigin.Slavic),
			Tuple.Create("Vallen", PersonNameOrigin.Slavic),
			Tuple.Create("Aditya", PersonNameOrigin.South_Asian),
			Tuple.Create("Bharat", PersonNameOrigin.South_Asian),
			Tuple.Create("Daud", PersonNameOrigin.South_Asian),
			Tuple.Create("Garuda", PersonNameOrigin.South_Asian),
			Tuple.Create("Girisha", PersonNameOrigin.South_Asian),
			Tuple.Create("Kapil", PersonNameOrigin.South_Asian),
			Tuple.Create("Narayan", PersonNameOrigin.South_Asian),
			Tuple.Create("Rajesh", PersonNameOrigin.South_Asian),
			Tuple.Create("Sahir", PersonNameOrigin.South_Asian),
			Tuple.Create("Shudra", PersonNameOrigin.South_Asian)
		};
		public static readonly Tuple<string, PersonNameOrigin>[] FemaleNames = new Tuple<string, PersonNameOrigin>[] {
			Tuple.Create("Adele", PersonNameOrigin.Common),
			Tuple.Create("Alanis", PersonNameOrigin.Common),
			Tuple.Create("Alice", PersonNameOrigin.Common),
			Tuple.Create("Alison", PersonNameOrigin.Common),
			Tuple.Create("Amanda", PersonNameOrigin.Common),
			Tuple.Create("Amber", PersonNameOrigin.Common),
			Tuple.Create("Amy", PersonNameOrigin.Common),
			Tuple.Create("Andrea", PersonNameOrigin.Common),
			Tuple.Create("Angela", PersonNameOrigin.Common),
			Tuple.Create("Anna", PersonNameOrigin.Common),
			Tuple.Create("April", PersonNameOrigin.Common),
			Tuple.Create("Ashley", PersonNameOrigin.Common),
			Tuple.Create("Ava", PersonNameOrigin.Common),
			Tuple.Create("Barbara", PersonNameOrigin.Common),
			Tuple.Create("Bethany", PersonNameOrigin.Common),
			Tuple.Create("Bonnie", PersonNameOrigin.Common),
			Tuple.Create("Bridget", PersonNameOrigin.Common),
			Tuple.Create("Brittany", PersonNameOrigin.Common),
			Tuple.Create("Candice", PersonNameOrigin.Common),
			Tuple.Create("Carla", PersonNameOrigin.Common),
			Tuple.Create("Carlie", PersonNameOrigin.Common),
			Tuple.Create("Carmen", PersonNameOrigin.Common),
			Tuple.Create("Caroline", PersonNameOrigin.Common),
			Tuple.Create("Carrie", PersonNameOrigin.Common),
			Tuple.Create("Cassandra", PersonNameOrigin.Common),
			Tuple.Create("Chantelle", PersonNameOrigin.Common),
			Tuple.Create("Charlotte", PersonNameOrigin.Common),
			Tuple.Create("Cheryl", PersonNameOrigin.Common),
			Tuple.Create("Chloe", PersonNameOrigin.Common),
			Tuple.Create("Christine", PersonNameOrigin.Common),
			Tuple.Create("Cindy", PersonNameOrigin.Common),
			Tuple.Create("Claire", PersonNameOrigin.Common),
			Tuple.Create("Clara", PersonNameOrigin.Common),
			Tuple.Create("Connie", PersonNameOrigin.Common),
			Tuple.Create("Cynthia", PersonNameOrigin.Common),
			Tuple.Create("Dakota", PersonNameOrigin.Common),
			Tuple.Create("Dana", PersonNameOrigin.Common),
			Tuple.Create("Dawn", PersonNameOrigin.Common),
			Tuple.Create("Debbie", PersonNameOrigin.Common),
			Tuple.Create("Dianne", PersonNameOrigin.Common),
			Tuple.Create("Donna", PersonNameOrigin.Common),
			Tuple.Create("Dora", PersonNameOrigin.Common),
			Tuple.Create("Edna", PersonNameOrigin.Common),
			Tuple.Create("Elena", PersonNameOrigin.Common),
			Tuple.Create("Elizabeth", PersonNameOrigin.Common),
			Tuple.Create("Ellen", PersonNameOrigin.Common),
			Tuple.Create("Emerald", PersonNameOrigin.Common),
			Tuple.Create("Emily", PersonNameOrigin.Common),
			Tuple.Create("Erica", PersonNameOrigin.Common),
			Tuple.Create("Erin", PersonNameOrigin.Common),
			Tuple.Create("Evelyn", PersonNameOrigin.Common),
			Tuple.Create("Felicity", PersonNameOrigin.Common),
			Tuple.Create("Flora", PersonNameOrigin.Common),
			Tuple.Create("Florence", PersonNameOrigin.Common),
			Tuple.Create("Gail", PersonNameOrigin.Common),
			Tuple.Create("Georgina", PersonNameOrigin.Common),
			Tuple.Create("Gina", PersonNameOrigin.Common),
			Tuple.Create("Gloria", PersonNameOrigin.Common),
			Tuple.Create("Grace", PersonNameOrigin.Common),
			Tuple.Create("Gwen", PersonNameOrigin.Common),
			Tuple.Create("Hazel", PersonNameOrigin.Common),
			Tuple.Create("Heather", PersonNameOrigin.Common),
			Tuple.Create("Heidi", PersonNameOrigin.Common),
			Tuple.Create("Helen", PersonNameOrigin.Common),
			Tuple.Create("Holly", PersonNameOrigin.Common),
			Tuple.Create("Irene", PersonNameOrigin.Common),
			Tuple.Create("Iris", PersonNameOrigin.Common),
			Tuple.Create("Isabelle", PersonNameOrigin.Common),
			Tuple.Create("Jacqueline", PersonNameOrigin.Common),
			Tuple.Create("Jane", PersonNameOrigin.Common),
			Tuple.Create("Jasmine", PersonNameOrigin.Common),
			Tuple.Create("Jennifer", PersonNameOrigin.Common),
			Tuple.Create("Jessica", PersonNameOrigin.Common),
			Tuple.Create("Jill", PersonNameOrigin.Common),
			Tuple.Create("Joan", PersonNameOrigin.Common),
			Tuple.Create("Jodi", PersonNameOrigin.Common),
			Tuple.Create("Josephine", PersonNameOrigin.Common),
			Tuple.Create("Joyce", PersonNameOrigin.Common),
			Tuple.Create("Juile", PersonNameOrigin.Common),
			Tuple.Create("Karen", PersonNameOrigin.Common),
			Tuple.Create("Kate", PersonNameOrigin.Common),
			Tuple.Create("Katherine", PersonNameOrigin.Common),
			Tuple.Create("Kathleen", PersonNameOrigin.Common),
			Tuple.Create("Kelsey", PersonNameOrigin.Common),
			Tuple.Create("Kimberly", PersonNameOrigin.Common),
			Tuple.Create("Krystal", PersonNameOrigin.Common),
			Tuple.Create("Laura", PersonNameOrigin.Common),
			Tuple.Create("Leah", PersonNameOrigin.Common),
			Tuple.Create("Lillian", PersonNameOrigin.Common),
			Tuple.Create("Linda", PersonNameOrigin.Common),
			Tuple.Create("Lisa", PersonNameOrigin.Common),
			Tuple.Create("Lois", PersonNameOrigin.Common),
			Tuple.Create("Lorainne", PersonNameOrigin.Common),
			Tuple.Create("Lori", PersonNameOrigin.Common),
			Tuple.Create("Louise", PersonNameOrigin.Common),
			Tuple.Create("Lucy", PersonNameOrigin.Common),
			Tuple.Create("Mabel", PersonNameOrigin.Common),
			Tuple.Create("Madeline", PersonNameOrigin.Common),
			Tuple.Create("Marcia", PersonNameOrigin.Common),
			Tuple.Create("Margaret", PersonNameOrigin.Common),
			Tuple.Create("Maria", PersonNameOrigin.Common),
			Tuple.Create("Marilyn", PersonNameOrigin.Common),
			Tuple.Create("Martha", PersonNameOrigin.Common),
			Tuple.Create("Mary", PersonNameOrigin.Common),
			Tuple.Create("Megan", PersonNameOrigin.Common),
			Tuple.Create("Melissa", PersonNameOrigin.Common),
			Tuple.Create("Meryl", PersonNameOrigin.Common),
			Tuple.Create("Mia", PersonNameOrigin.Common),
			Tuple.Create("Micah", PersonNameOrigin.Common),
			Tuple.Create("Michelle", PersonNameOrigin.Common),
			Tuple.Create("Mildred", PersonNameOrigin.Common),
			Tuple.Create("Misty", PersonNameOrigin.Common),
			Tuple.Create("Molly", PersonNameOrigin.Common),
			Tuple.Create("Monica", PersonNameOrigin.Common),
			Tuple.Create("Nancy", PersonNameOrigin.Common),
			Tuple.Create("Naomi", PersonNameOrigin.Common),
			Tuple.Create("Natalie", PersonNameOrigin.Common),
			Tuple.Create("Natasha", PersonNameOrigin.Common),
			Tuple.Create("Nicole", PersonNameOrigin.Common),
			Tuple.Create("Nina", PersonNameOrigin.Common),
			Tuple.Create("Nora", PersonNameOrigin.Common),
			Tuple.Create("Olivia", PersonNameOrigin.Common),
			Tuple.Create("Paige", PersonNameOrigin.Common),
			Tuple.Create("Pamela", PersonNameOrigin.Common),
			Tuple.Create("Patricia", PersonNameOrigin.Common),
			Tuple.Create("Paula", PersonNameOrigin.Common),
			Tuple.Create("Peggy", PersonNameOrigin.Common),
			Tuple.Create("Penelope", PersonNameOrigin.Common),
			Tuple.Create("Piper", PersonNameOrigin.Common),
			Tuple.Create("Rachel", PersonNameOrigin.Common),
			Tuple.Create("Ramona", PersonNameOrigin.Common),
			Tuple.Create("Rebecca", PersonNameOrigin.Common),
			Tuple.Create("Renee", PersonNameOrigin.Common),
			Tuple.Create("Rhonda", PersonNameOrigin.Common),
			Tuple.Create("Rita", PersonNameOrigin.Common),
			Tuple.Create("Rose", PersonNameOrigin.Common),
			Tuple.Create("Roxanne", PersonNameOrigin.Common),
			Tuple.Create("Ruby", PersonNameOrigin.Common),
			Tuple.Create("Ruth", PersonNameOrigin.Common),
			Tuple.Create("Sabrina", PersonNameOrigin.Common),
			Tuple.Create("Sally", PersonNameOrigin.Common),
			Tuple.Create("Samantha", PersonNameOrigin.Common),
			Tuple.Create("Sandra", PersonNameOrigin.Common),
			Tuple.Create("Sarah", PersonNameOrigin.Common),
			Tuple.Create("Sharon", PersonNameOrigin.Common),
			Tuple.Create("Skye", PersonNameOrigin.Common),
			Tuple.Create("Sonia", PersonNameOrigin.Common),
			Tuple.Create("Stephanie", PersonNameOrigin.Common),
			Tuple.Create("Susan", PersonNameOrigin.Common),
			Tuple.Create("Tabitha", PersonNameOrigin.Common),
			Tuple.Create("Tamara", PersonNameOrigin.Common),
			Tuple.Create("Tanya", PersonNameOrigin.Common),
			Tuple.Create("Tara", PersonNameOrigin.Common),
			Tuple.Create("Teresa", PersonNameOrigin.Common),
			Tuple.Create("Tessa", PersonNameOrigin.Common),
			Tuple.Create("Thelma", PersonNameOrigin.Common),
			Tuple.Create("Theresa", PersonNameOrigin.Common),
			Tuple.Create("Tiffany", PersonNameOrigin.Common),
			Tuple.Create("Tina", PersonNameOrigin.Common),
			Tuple.Create("Ursula", PersonNameOrigin.Common),
			Tuple.Create("Valerie", PersonNameOrigin.Common),
			Tuple.Create("Vanessa", PersonNameOrigin.Common),
			Tuple.Create("Victoria", PersonNameOrigin.Common),
			Tuple.Create("Violet", PersonNameOrigin.Common),
			Tuple.Create("Virginia", PersonNameOrigin.Common),
			Tuple.Create("Wendy", PersonNameOrigin.Common),
			Tuple.Create("Whitney", PersonNameOrigin.Common),
			Tuple.Create("Winona", PersonNameOrigin.Common),
			Tuple.Create("Yvonne", PersonNameOrigin.Common),
			Tuple.Create("Zoey", PersonNameOrigin.Common),
			Tuple.Create("Abeje", PersonNameOrigin.African),
			Tuple.Create("Ashanti", PersonNameOrigin.African),
			Tuple.Create("Ezewa", PersonNameOrigin.African),
			Tuple.Create("Ibena", PersonNameOrigin.African),
			Tuple.Create("Issa", PersonNameOrigin.African),
			Tuple.Create("Kida", PersonNameOrigin.African),
			Tuple.Create("Mawusi", PersonNameOrigin.African),
			Tuple.Create("Osa", PersonNameOrigin.African),
			Tuple.Create("Suma", PersonNameOrigin.African),
			Tuple.Create("Tiwa", PersonNameOrigin.African),
			Tuple.Create("Chun", PersonNameOrigin.Chinese),
			Tuple.Create("Hùifang", PersonNameOrigin.Chinese),
			Tuple.Create("Lì húa", PersonNameOrigin.Chinese),
			Tuple.Create("Lin", PersonNameOrigin.Chinese),
			Tuple.Create("Mei", PersonNameOrigin.Chinese),
			Tuple.Create("Ruolan", PersonNameOrigin.Chinese),
			Tuple.Create("Suyin", PersonNameOrigin.Chinese),
			Tuple.Create("Xiaoli", PersonNameOrigin.Chinese),
			Tuple.Create("Yingtai", PersonNameOrigin.Chinese),
			Tuple.Create("Zhilan", PersonNameOrigin.Chinese),
			Tuple.Create("Abrielle", PersonNameOrigin.French),
			Tuple.Create("Charmane", PersonNameOrigin.French),
			Tuple.Create("Desiree", PersonNameOrigin.French),
			Tuple.Create("Eloise", PersonNameOrigin.French),
			Tuple.Create("Lizette", PersonNameOrigin.French),
			Tuple.Create("Lucienne", PersonNameOrigin.French),
			Tuple.Create("Margo", PersonNameOrigin.French),
			Tuple.Create("Peridot", PersonNameOrigin.French),
			Tuple.Create("Solange", PersonNameOrigin.French),
			Tuple.Create("Voletta", PersonNameOrigin.French),
			Tuple.Create("Athena", PersonNameOrigin.Greek),
			Tuple.Create("Baslikike", PersonNameOrigin.Greek),
			Tuple.Create("Soussana", PersonNameOrigin.Greek),
			Tuple.Create("Despina", PersonNameOrigin.Greek),
			Tuple.Create("Zinovia", PersonNameOrigin.Greek),
			Tuple.Create("Elektra", PersonNameOrigin.Greek),
			Tuple.Create("Ioanna", PersonNameOrigin.Greek),
			Tuple.Create("Sotiria", PersonNameOrigin.Greek),
			Tuple.Create("Kyriake", PersonNameOrigin.Greek),
			Tuple.Create("Panagiota", PersonNameOrigin.Greek),
			Tuple.Create("Aisling", PersonNameOrigin.Irish),
			Tuple.Create("Aoife", PersonNameOrigin.Irish),
			Tuple.Create("Ciara", PersonNameOrigin.Irish),
			Tuple.Create("Clodagh", PersonNameOrigin.Irish),
			Tuple.Create("Eimear", PersonNameOrigin.Irish),
			Tuple.Create("Keeva", PersonNameOrigin.Irish),
			Tuple.Create("Niamh", PersonNameOrigin.Irish),
			Tuple.Create("Saoirse", PersonNameOrigin.Irish),
			Tuple.Create("Sinead", PersonNameOrigin.Irish),
			Tuple.Create("Sive", PersonNameOrigin.Irish),
			Tuple.Create("Alessia", PersonNameOrigin.Italian),
			Tuple.Create("Azzurra", PersonNameOrigin.Italian),
			Tuple.Create("Benedetta", PersonNameOrigin.Italian),
			Tuple.Create("Flavia", PersonNameOrigin.Italian),
			Tuple.Create("Ilaria", PersonNameOrigin.Italian),
			Tuple.Create("Lucia", PersonNameOrigin.Italian),
			Tuple.Create("Martina", PersonNameOrigin.Italian),
			Tuple.Create("Paola", PersonNameOrigin.Italian),
			Tuple.Create("Sofia", PersonNameOrigin.Italian),
			Tuple.Create("Valeria", PersonNameOrigin.Italian),
			Tuple.Create("Akari", PersonNameOrigin.Japanese),
			Tuple.Create("Hana", PersonNameOrigin.Japanese),
			Tuple.Create("Himari", PersonNameOrigin.Japanese),
			Tuple.Create("Koharu", PersonNameOrigin.Japanese),
			Tuple.Create("Rina", PersonNameOrigin.Japanese),
			Tuple.Create("Saki", PersonNameOrigin.Japanese),
			Tuple.Create("Sakura", PersonNameOrigin.Japanese),
			Tuple.Create("Yui", PersonNameOrigin.Japanese),
			Tuple.Create("Yume", PersonNameOrigin.Japanese),
			Tuple.Create("Yuna", PersonNameOrigin.Japanese),
			Tuple.Create("Adriana", PersonNameOrigin.Latino),
			Tuple.Create("Alejandra", PersonNameOrigin.Latino),
			Tuple.Create("Amalia", PersonNameOrigin.Latino),
			Tuple.Create("Consuela", PersonNameOrigin.Latino),
			Tuple.Create("Fiorella", PersonNameOrigin.Latino),
			Tuple.Create("Gabriela", PersonNameOrigin.Latino),
			Tuple.Create("Josefina", PersonNameOrigin.Latino),
			Tuple.Create("Manuela", PersonNameOrigin.Latino),
			Tuple.Create("Mariana", PersonNameOrigin.Latino),
			Tuple.Create("Salome", PersonNameOrigin.Latino),
			Tuple.Create("Aiza", PersonNameOrigin.Middle_Eastern),
			Tuple.Create("Anam", PersonNameOrigin.Middle_Eastern),
			Tuple.Create("Ayesha", PersonNameOrigin.Middle_Eastern),
			Tuple.Create("Eshaal", PersonNameOrigin.Middle_Eastern),
			Tuple.Create("Fatima", PersonNameOrigin.Middle_Eastern),
			Tuple.Create("Khadija", PersonNameOrigin.Middle_Eastern),
			Tuple.Create("Rabia", PersonNameOrigin.Middle_Eastern),
			Tuple.Create("Saba", PersonNameOrigin.Middle_Eastern),
			Tuple.Create("Zainab", PersonNameOrigin.Middle_Eastern),
			Tuple.Create("Zoya", PersonNameOrigin.Middle_Eastern),
			Tuple.Create("Alina", PersonNameOrigin.Russian),
			Tuple.Create("Anastasiya", PersonNameOrigin.Russian),
			Tuple.Create("Belka", PersonNameOrigin.Russian),
			Tuple.Create("Elvira", PersonNameOrigin.Russian),
			Tuple.Create("Izolda", PersonNameOrigin.Russian),
			Tuple.Create("Kseniya", PersonNameOrigin.Russian),
			Tuple.Create("Lidiya", PersonNameOrigin.Russian),
			Tuple.Create("Olga", PersonNameOrigin.Russian),
			Tuple.Create("Svetlana", PersonNameOrigin.Russian),
			Tuple.Create("Zhanna", PersonNameOrigin.Russian),
			Tuple.Create("Agnetha", PersonNameOrigin.Scandinavian),
			Tuple.Create("Britta", PersonNameOrigin.Scandinavian),
			Tuple.Create("Freya", PersonNameOrigin.Scandinavian),
			Tuple.Create("Gretel", PersonNameOrigin.Scandinavian),
			Tuple.Create("Helga", PersonNameOrigin.Scandinavian),
			Tuple.Create("Ingrid", PersonNameOrigin.Scandinavian),
			Tuple.Create("Karah", PersonNameOrigin.Scandinavian),
			Tuple.Create("Liv", PersonNameOrigin.Scandinavian),
			Tuple.Create("Sigrun", PersonNameOrigin.Scandinavian),
			Tuple.Create("Tuuri", PersonNameOrigin.Scandinavian),
			Tuple.Create("Chessa", PersonNameOrigin.Slavic),
			Tuple.Create("Danica", PersonNameOrigin.Slavic),
			Tuple.Create("Dannica", PersonNameOrigin.Slavic),
			Tuple.Create("Hedy", PersonNameOrigin.Slavic),
			Tuple.Create("Iva", PersonNameOrigin.Slavic),
			Tuple.Create("Lala", PersonNameOrigin.Slavic),
			Tuple.Create("Marya", PersonNameOrigin.Slavic),
			Tuple.Create("Miloslava", PersonNameOrigin.Slavic),
			Tuple.Create("Neda", PersonNameOrigin.Slavic),
			Tuple.Create("Vasilisa", PersonNameOrigin.Slavic),
			Tuple.Create("Apala", PersonNameOrigin.South_Asian),
			Tuple.Create("Dharma", PersonNameOrigin.South_Asian),
			Tuple.Create("Indira", PersonNameOrigin.South_Asian),
			Tuple.Create("Jayanti", PersonNameOrigin.South_Asian),
			Tuple.Create("Maisha", PersonNameOrigin.South_Asian),
			Tuple.Create("Priya", PersonNameOrigin.South_Asian),
			Tuple.Create("Rani", PersonNameOrigin.South_Asian),
			Tuple.Create("Sakari", PersonNameOrigin.South_Asian),
			Tuple.Create("Soma", PersonNameOrigin.South_Asian),
			Tuple.Create("Yasminder", PersonNameOrigin.South_Asian),
		};
		public static readonly Tuple<string, PersonNameOrigin>[] NeutralNames = new Tuple<string, PersonNameOrigin>[] {
			Tuple.Create("Jamie", PersonNameOrigin.Common),
			Tuple.Create("Robin", PersonNameOrigin.Common),
			Tuple.Create("Charlie", PersonNameOrigin.Common),
			Tuple.Create("Francis", PersonNameOrigin.Common),
			Tuple.Create("Alex", PersonNameOrigin.Common),
			Tuple.Create("Maurice", PersonNameOrigin.Common),
			Tuple.Create("Marion", PersonNameOrigin.Common),
			Tuple.Create("Reggie", PersonNameOrigin.Common),
			Tuple.Create("Leslie", PersonNameOrigin.Common),
			Tuple.Create("Casey", PersonNameOrigin.Common),
			Tuple.Create("Sydney", PersonNameOrigin.Common),
			Tuple.Create("Tracy", PersonNameOrigin.Common),
			Tuple.Create("Taylor", PersonNameOrigin.Common),
			Tuple.Create("Shannon", PersonNameOrigin.Common),
			Tuple.Create("Kerry", PersonNameOrigin.Common),
			Tuple.Create("Courtney", PersonNameOrigin.Common),
			Tuple.Create("Vivian", PersonNameOrigin.Common),
			Tuple.Create("Jordan", PersonNameOrigin.Common),
			Tuple.Create("Peyton", PersonNameOrigin.Common),
			Tuple.Create("Ash", PersonNameOrigin.Common),
			Tuple.Create("Ainsley", PersonNameOrigin.Common),
			Tuple.Create("Bailey", PersonNameOrigin.Common),
			Tuple.Create("River", PersonNameOrigin.Common),
			Tuple.Create("Avery", PersonNameOrigin.Common),
			Tuple.Create("Skyler", PersonNameOrigin.Common),
			Tuple.Create("Kendall", PersonNameOrigin.Common),
			Tuple.Create("Quinn", PersonNameOrigin.Common),
			Tuple.Create("Harley", PersonNameOrigin.Common),
			Tuple.Create("Reese", PersonNameOrigin.Common),
			Tuple.Create("Justice", PersonNameOrigin.Common),
			Tuple.Create("Carey", PersonNameOrigin.Common),
			Tuple.Create("Blair", PersonNameOrigin.Common),
			Tuple.Create("Emery", PersonNameOrigin.Common),
			Tuple.Create("Rowan", PersonNameOrigin.Common),
			Tuple.Create("Phoenix", PersonNameOrigin.Common),
			Tuple.Create("Tory", PersonNameOrigin.Common),
			Tuple.Create("Finley", PersonNameOrigin.Common),
			Tuple.Create("Riley", PersonNameOrigin.Common),
			Tuple.Create("Channing", PersonNameOrigin.Common),
			Tuple.Create("Oakley", PersonNameOrigin.Common),
			Tuple.Create("Arin", PersonNameOrigin.Common),
			Tuple.Create("Aires", PersonNameOrigin.Common),
			Tuple.Create("Sutton", PersonNameOrigin.Common),
			Tuple.Create("Tatum", PersonNameOrigin.Common),
			Tuple.Create("Alexis", PersonNameOrigin.Common),
			Tuple.Create("Brady", PersonNameOrigin.Common),
			Tuple.Create("Keegan", PersonNameOrigin.Common),
			Tuple.Create("Logan", PersonNameOrigin.Common),
			Tuple.Create("Reagan", PersonNameOrigin.Common),
			Tuple.Create("Scout", PersonNameOrigin.Common)
		};

		private static List<string> TappedNames = new List<string>();
		private static string GetGenderName(Gender gender, PersonNameOrigin origin, string exclude = null)
		{
			string found = null;

			switch (gender)
			{
			case Gender.Female:
				found = Utils.Pick(FemaleNames.Where((Tuple) => Tuple.Item2 == origin).ToArray()).Item1;
				break;

			case Gender.Male:
				found = Utils.Pick(MaleNames.Where((Tuple) => Tuple.Item2 == origin).ToArray()).Item1;
				break;
			}

			if (exclude != null && found == exclude)
				return GetGenderName(gender, origin, exclude);

			return found;
		}
		public static PersonName Create(Gender gender)
		{
			var origin = Utils.Pick<PersonNameOrigin>();
			var firstName = GetGenderName(gender, origin);

			string secondName = null;
			// 30% chance for "common" names to have a middle/second name
			if (origin == PersonNameOrigin.Common && Utils.Rnd.Next(100) <= 30)
			{
				secondName = GetGenderName(gender, origin, firstName);
			}

			var lastName = Utils.Pick(LastNames.Where((Tuple) => Tuple.Item2 == origin).ToArray()).Item1;

			// Prevent first/last combos from being repeated
			if (TappedNames.Contains(firstName + lastName))
			{
				return Create(gender);
			}
			else
			{
				TappedNames.Add(firstName + lastName);
			}

			return new PersonName(firstName, secondName, lastName, origin);
		}

		private static Tuple<string, string, string, PersonNameOrigin> Derive(Gender gender, PersonName mother, PersonName father)
		{
			PersonNameOrigin origin;

			string last = null;

			// 80% chance of taking the father's last name
			if (Utils.Rnd.Next(100) <= 85)
			{
				origin = father.Origin;
				last = father.Last;
			}
			else if (Utils.Rnd.Next(100) <= 10)
			{
				origin = mother.Origin;
				last = mother.Last;
			}
			else
			{
				origin = Utils.Pick(mother.Origin, father.Origin);

				if (mother.Last.Contains("-") || father.Last.Contains("-"))
				{
					last = Utils.Pick(mother.Last, father.Last);
				}
				else
				{
					last = father.Last + '-' + mother.Last;
				}
			}

			var first = GetGenderName(gender, origin);

			if (TappedNames.Contains(first + last))
				return Derive(gender, mother, father);

			string second = null;
			// 30% chance for "common" names to have a middle/second name
			if (origin == PersonNameOrigin.Common && Utils.Rnd.Next(100) <= 30)
			{
				second = GetGenderName(gender, origin, first);
			}

			return new Tuple<string, string, string, PersonNameOrigin>(first, second, last, origin);
		}

		public string First { get; private set; }
		public string Second { get; private set; }
		public string Last { get; private set; }
		public PersonNameOrigin Origin { get; private set; }

		private PersonName(string first, string second, string last, PersonNameOrigin origin)
		{
			First = first;
			Second = second;
			Last = last;
			Origin = origin;
		}

		public PersonName(Gender gender, PersonName mother, PersonName father)
		{
			var name = Derive(gender, mother, father);
			First = name.Item1;
			Second = name.Item2;
			Last = name.Item3;
			Origin = name.Item4;
		}

		public override string ToString()
		{
			if (Second == null)
				return First + ' ' + Last; // + " (" + Origin + ')';

			return First + ' ' + Second + ' ' + Last; // + " (" + Origin + ')';
		}
	}
}
